create table if not exists qfbap_dm.dm_user_visit(
user_id int,
latest_pc_visit_date            string,
latest_pc_visit_session         string,
latest_pc_cookies               string,
latest_pc_pv                    int,
latest_pc_browser_name          string,
latest_pc_visit_os              string,
first_pc_visit_date             string,
first_pc_visit_session          string,
first_pc_cookies                string,
first_pc_pv                     int,
first_pc_browser_name           string,
first_pc_visit_os               string,
day7_pc_cnt                     int,
day15_pc_cnt                    int,
month1_pc_cnt                   int,
month2_pc_cnt                   int,
month3_pc_cnt                   int,
month1_pc_days                  int,
month1_pc_pv                    int,
month1_pc_avg_pv                DOUBLE,
month1_pc_hour025_cnt           int,
month1_pc_hour627_cnt           int,
month1_pc_hour829_cnt           int,
month1_pc_hour10211_cnt         int,
month1_pc_hour12213_cnt         int,
month1_pc_hour14216_cnt         int,
month1_pc_hour17219_cnt         int,
month1_pc_hour18219_cnt         int,
month1_pc_hour20221_cnt         int,
month1_pc_hour22223_cnt         int,
month1_pc_diff_ip_cnt           int,
month1_pc_common_ip             string,
month1_pc_diff_cookie_cnt       int,
month1_pc_common_cookie         string,
month1_pc_common_browser_name   string,
month1_pc_common_os             string,
latest_app_visit_date           string,
latest_app_name                 string,
latest_app_visit_os             string,
first_app_visit_date            string,
first_app_name                  string,
first_app_visit_os              string,
first_app_visit_ip              string,
day7_app_cnt                    int,
day15_app_cnt                   int,
month1_app_cnt                  int,
month2_app_cnt                  int,
month3_app_cnt                  int,
month1_app_hour025_cnt          int,
month1_app_hour627_cnt          int,
month1_app_hour829_cnt          int,
month1_app_hour10211_cnt        int,
month1_app_hour12213_cnt        int,
month1_app_hour14215_cnt        int,
month1_app_hour16217_cnt        int,
month1_app_hour18219_cnt        int,
month1_app_hour20221_cnt        int,
month1_app_hour22223_cnt        int,
latest_visit_ip                 string,
latest_city                     string,
latest_province                 string,
first_visit_ip                  string,
first_city                      string,
first_province                  string,
import_dt                       string
)
partitioned by (dt date)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
   WITH SERDEPROPERTIES (
        'field.delim'='\t',
        'serialization.null.format'='')
stored as textfile;
